import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

import "./globals.css";

const raleway = Raleway({
	weight: ["400", "700"],
	variable: "--font-raleway",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Keleidoscope",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${raleway.variable} antialiased`}>
				<Nav />
				{children}
				<Footer />
			</body>
		</html>
	);
}
